---
# Source: api-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    helm.sh/chart: api-gateway-1.0.1
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway
    app.kubernetes.io/version: "4.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/instance: api-gateway
  template:
    metadata:
      annotations:
        timestamp: "20240220175701"
        prometheus.io/path: "__stats"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/instance: api-gateway
    spec:
      volumes:
        - name: config
          configMap:
            name: api-gateway-configmap
      serviceAccountName: api-gateway
      securityContext:
        {}
      containers:
        - name: api-gateway
          securityContext:
            {}
          image: "891377294027.dkr.ecr.us-east-1.amazonaws.com/api-gateway:staging"
          imagePullPolicy: Always
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
          env:
          - name: KRAKEND_PORT
            value: "8080"
          - name: AUTH_DOMAIN
            value: dev-26i1fsf2m1n6hqk1.us.auth0.com
          - name: AUTH_AUDIENCE
            value: https://dev-26i1fsf2m1n6hqk1.us.auth0.com/api/v2/
          - name: ENV
            value: staging
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi

